
/**
 * SummaryPage.jsx — Production summary with:
 * - Unique meeting ID / document code
 * - Real notes from session (persisted)
 * - Functional copy + download .txt
 * - AI summary, calendar links
 * - Professional dark background
 */
import React, { useState, useCallback, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";

const API = import.meta.env.VITE_SOCKET_URL || "http://localhost:4000";

// Generate deterministic document code from roomId + date
function generateDocCode(roomId, date) {
  const d    = new Date(date);
  const yy   = String(d.getFullYear()).slice(-2);
  const mm   = String(d.getMonth() + 1).padStart(2, "0");
  const dd   = String(d.getDate()).padStart(2, "0");
  const base = (roomId || "ROOM").replace(/[^A-Z0-9]/gi, "").toUpperCase().slice(0, 6);
  return `FM-${base}-${yy}${mm}${dd}`;
}

function fmtDuration(s) {
  const m = Math.floor(Math.max(0, s) / 60);
  const sec = Math.max(0, s) % 60;
  return `${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}`;
}

function fmtDate(date) {
  return new Date(date).toLocaleDateString("en-US", {
    weekday:"long", year:"numeric", month:"long", day:"numeric",
  });
}

function fmtTime(date) {
  return new Date(date).toLocaleTimeString("en-US", { hour:"2-digit", minute:"2-digit" });
}

export default function SummaryPage({ summary, onNewMeeting, onHome }) {
  const {
    roomId       = "ROOM",
    roomName     = "Meeting",
    duration     = 0,
    participants = [],
    notes        = "",
    date         = new Date(),
  } = summary || {};

  // Try to recover notes from localStorage if empty
  const [resolvedNotes, setResolvedNotes] = useState(() => {
    if (notes && notes.trim()) return notes;
    try {
      const stored = localStorage.getItem(`fm_notes_${roomId}`);
      return stored || notes || "";
    } catch { return notes || ""; }
  });

  const docCode = generateDocCode(roomId, date);

  const [copied,    setCopied]    = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiSummary, setAiSummary] = useState("");
  const [calLinks,  setCalLinks]  = useState(null);
  const [showCal,   setShowCal]   = useState(false);
  const [noteEdit,  setNoteEdit]  = useState(resolvedNotes);

  // Keep noteEdit in sync
  useEffect(() => { setNoteEdit(resolvedNotes); }, [resolvedNotes]);

  // ── Build full document text ──────────────────────────────────────────────
  const buildDoc = useCallback((extraAI = "") => {
    const lines = [
      `╔══════════════════════════════════════════════════╗`,
      `║           FOCUSMEET — MEETING SUMMARY            ║`,
      `╚══════════════════════════════════════════════════╝`,
      ``,
      `Document Code : ${docCode}`,
      `Meeting Name  : ${roomName}`,
      `Room ID       : ${roomId}`,
      `Date          : ${fmtDate(date)}`,
      `Time          : ${fmtTime(date)}`,
      `Duration      : ${fmtDuration(duration)}`,
      `Participants  : ${participants.length}`,
      ``,
      `${"─".repeat(52)}`,
      `PARTICIPANTS`,
      `${"─".repeat(52)}`,
      ...participants.map((p, i) =>
        `  ${i === 0 ? "★" : "•"} ${p.name}${i === 0 ? " (Host)" : ""}  ·  ${fmtDuration(duration)}`
      ),
      participants.length === 0 ? "  (no participant data)" : "",
      ``,
      `${"─".repeat(52)}`,
      `SHARED NOTES`,
      `${"─".repeat(52)}`,
      noteEdit.trim() || "(No notes were added during this session.)",
      ``,
      ...(extraAI ? [
        `${"─".repeat(52)}`,
        `AI SUMMARY`,
        `${"─".repeat(52)}`,
        extraAI,
        ``,
      ] : []),
      `${"─".repeat(52)}`,
      `Generated by FocusMeet  ·  focusmeet.app`,
      `Document Code: ${docCode}`,
      `${"─".repeat(52)}`,
    ];
    return lines.join("\n");
  }, [docCode, roomName, roomId, date, duration, participants, noteEdit, aiSummary]);

  const handleCopy = useCallback(async () => {
    const text = buildDoc(aiSummary);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2600);
    } catch {
      // Fallback for browsers that block clipboard
      const ta = document.createElement("textarea");
      ta.value = text;
      ta.style.position = "fixed"; ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select(); document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2600);
    }
  }, [buildDoc, aiSummary]);

  const handleDownload = useCallback(() => {
    const text  = buildDoc(aiSummary);
    const slug  = roomName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    const fname = `${docCode}-${slug}.txt`;
    const blob  = new Blob([text], { type:"text/plain;charset=utf-8" });
    const url   = URL.createObjectURL(blob);
    const a     = document.createElement("a");
    a.href = url; a.download = fname;
    document.body.appendChild(a); a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [buildDoc, aiSummary, docCode, roomName]);

  const generateAI = useCallback(async () => {
    if (!noteEdit.trim() || aiLoading) return;
    setAiLoading(true); setAiSummary("");
    try {
      const token = localStorage.getItem("fm_token");
      const r = await fetch(`${API}/api/ai/summary`, {
        method: "POST",
        headers: { "Content-Type":"application/json", Authorization:`Bearer ${token}` },
        body: JSON.stringify({ notes: noteEdit, roomName, duration }),
      });
      const d = await r.json();
      setAiSummary(r.ok ? d.summary : "⚠️ " + (d.error || "AI failed"));
    } catch { setAiSummary("⚠️ Network error — add OPENAI_API_KEY to backend .env"); }
    finally { setAiLoading(false); }
  }, [noteEdit, roomName, duration, aiLoading]);

  const fetchCalLinks = useCallback(async () => {
    setShowCal(s => !s);
    if (calLinks) return;
    try {
      const token = localStorage.getItem("fm_token");
      const r = await fetch(`${API}/api/calendar/link`, {
        method:"POST",
        headers:{ "Content-Type":"application/json", Authorization:`Bearer ${token}` },
        body: JSON.stringify({ roomId, roomName, startTime: Date.now() + 3600000, durationMin: 25 }),
      });
      const d = await r.json();
      if (r.ok) setCalLinks(d);
    } catch {}
  }, [roomId, roomName, calLinks]);

  const pColors = ["#6366f1","#06b6d4","#8b5cf6","#10b981","#f59e0b","#ec4899"];

  return (
    <div className="relative min-h-screen py-16 px-4 overflow-hidden" style={{ background:"#030507" }}>
      {/* ── Background — dark aurora / gradient */}
      {/* Asset: summary-bg.jpg */}
      <div className="absolute inset-0 z-0">
        <div className="absolute inset-0" style={{
          backgroundImage:"url('/assets/images/summary-bg.jpg')",
          backgroundSize:"cover", backgroundPosition:"center", opacity:0.14,
        }}/>
        <div className="absolute inset-0" style={{ background:"radial-gradient(ellipse 80% 60% at 50% 20%, rgba(16,185,129,0.10) 0%, transparent 70%)" }}/>
        <div className="absolute inset-0" style={{ background:"radial-gradient(ellipse 60% 40% at 80% 80%, rgba(99,102,241,0.08) 0%, transparent 70%)" }}/>
        <div className="absolute inset-x-0 top-0 h-32" style={{ background:"linear-gradient(180deg,#030507,transparent)" }}/>
      </div>

      <div className="relative z-10 max-w-2xl mx-auto">
        {/* ── Success header ── */}
        <motion.div initial={{ opacity:0, y:24 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.65 }} className="text-center mb-10">
          <div className="inline-flex mb-6">
            <div className="w-20 h-20 rounded-3xl flex items-center justify-center"
              style={{ background:"rgba(16,185,129,0.14)", border:"1px solid rgba(16,185,129,0.28)", boxShadow:"0 0 40px rgba(16,185,129,0.18)" }}>
              <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#34d399" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <polyline points="20 6 9 17 4 12"/>
              </svg>
            </div>
          </div>
          <h1 className="font-bold text-white mb-1"
            style={{ fontSize:"clamp(1.7rem,3vw,2.4rem)", letterSpacing:"-0.04em" }}>
            {roomName}
          </h1>
          <p className="text-white/35 text-sm mb-3">{fmtDate(date)} · {fmtTime(date)}</p>

          {/* ── Unique Document Code ── */}
          <div className="inline-flex items-center gap-2.5 px-4 py-2 rounded-xl"
            style={{ background:"rgba(99,102,241,0.12)", border:"1px solid rgba(99,102,241,0.25)" }}>
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#a5b4fc" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/>
            </svg>
            <span className="text-sm font-bold text-indigo-300 tracking-wider font-mono">{docCode}</span>
            <button
              onClick={() => navigator.clipboard.writeText(docCode)}
              className="text-[9px] text-indigo-400/60 hover:text-indigo-300 transition-colors ml-1"
              title="Copy code">
              copy
            </button>
          </div>
        </motion.div>

        {/* ── Stats ── */}
        <motion.div initial={{ opacity:0, y:16 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.55, delay:0.1 }}
          className="grid grid-cols-3 gap-3 mb-5">
          {[
            { label:"Duration",     value: fmtDuration(duration) },
            { label:"Participants", value: participants.length || "—" },
            { label:"Notes",        value: noteEdit ? noteEdit.split("\n").filter(Boolean).length : 0 },
          ].map((s, i) => (
            <div key={i} className="glass rounded-2xl p-5 text-center">
              <div className="text-2xl font-bold text-white mb-1" style={{ letterSpacing:"-0.05em" }}>{s.value}</div>
              <div className="text-[9px] font-bold uppercase tracking-widest text-white/25">{s.label}</div>
            </div>
          ))}
        </motion.div>

        {/* ── Participants ── */}
        {participants.length > 0 && (
          <motion.div initial={{ opacity:0, y:14 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.5, delay:0.15 }}
            className="glass rounded-2xl p-6 mb-4">
            <SLabel icon="👥" text="Participants"/>
            <div className="mt-3 space-y-3">
              {participants.map((p, i) => (
                <div key={i} className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-full flex items-center justify-center text-xs font-bold flex-shrink-0"
                    style={{ background:`${p.color || pColors[i % 6]}22`, color: p.color || pColors[i % 6], border:`1px solid ${p.color || pColors[i % 6]}35` }}>
                    {(p.initials || (p.name || "?").slice(0, 2)).toUpperCase()}
                  </div>
                  <span className="flex-1 text-sm text-white/72 font-medium">{p.name}
                    {i === 0 && <span className="ml-2 text-[9px] font-bold text-indigo-300 bg-indigo-500/15 px-1.5 py-0.5 rounded">Host</span>}
                  </span>
                  <span className="text-xs text-white/25 font-mono">{fmtDuration(duration)}</span>
                </div>
              ))}
            </div>
          </motion.div>
        )}

        {/* ── Notes — editable for corrections ── */}
        <motion.div initial={{ opacity:0, y:14 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.5, delay:0.2 }}
          className="glass rounded-2xl p-6 mb-4">
          <div className="flex items-center justify-between mb-3">
            <SLabel icon="📝" text="Shared notes"/>
            <span className="text-[9px] text-white/22">{noteEdit.length} chars · editable</span>
          </div>
          <textarea
            value={noteEdit}
            onChange={e => setNoteEdit(e.target.value)}
            placeholder="No notes were added during this session."
            className="w-full h-36 text-sm text-white/55 leading-relaxed resize-none outline-none rounded-xl p-3"
            style={{
              background:"rgba(255,255,255,0.03)",
              border:"1px solid rgba(255,255,255,0.08)",
              fontFamily:"inherit",
              lineHeight:1.65,
            }}
            onFocus={e => {
              e.target.style.borderColor = "rgba(99,102,241,0.45)";
              e.target.style.boxShadow   = "0 0 0 3px rgba(99,102,241,0.10)";
            }}
            onBlur={e => {
              e.target.style.borderColor = "rgba(255,255,255,0.08)";
              e.target.style.boxShadow   = "none";
            }}
          />
          <p className="text-[9px] text-white/20 mt-1.5 px-1">You can edit notes before downloading — changes are not synced back to the room.</p>
        </motion.div>

        {/* ── AI Summary ── */}
        <motion.div initial={{ opacity:0, y:14 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.5, delay:0.25 }}
          className="glass rounded-2xl p-6 mb-4">
          <div className="flex items-center justify-between mb-3">
            <SLabel icon="✨" text="AI summary"/>
            {noteEdit.trim() && (
              <button onClick={generateAI} disabled={aiLoading}
                className="text-[10px] font-bold px-3 py-1.5 rounded-lg transition-all disabled:opacity-40"
                style={{ background:"rgba(99,102,241,0.18)", border:"1px solid rgba(99,102,241,0.30)", color:"#a5b4fc" }}>
                {aiLoading ? "Generating…" : "Generate"}
              </button>
            )}
          </div>
          {aiSummary ? (
            <div className="text-sm text-white/52 leading-relaxed whitespace-pre-wrap p-3 rounded-xl"
              style={{ background:"rgba(99,102,241,0.07)", border:"1px solid rgba(99,102,241,0.13)" }}>
              {aiSummary}
            </div>
          ) : (
            <p className="text-white/20 text-xs italic">
              {noteEdit.trim()
                ? "Click Generate to create a structured AI summary of your notes."
                : "Add notes during meetings to enable AI summaries."
              }
            </p>
          )}
        </motion.div>

        {/* ── Export ── */}
        <motion.div initial={{ opacity:0, y:14 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.5, delay:0.3 }}
          className="glass rounded-2xl p-6 mb-5">
          <SLabel icon="⬇️" text="Export & share"/>

          {/* Document preview badge */}
          <div className="mt-3 mb-4 px-3 py-2 rounded-lg flex items-center gap-2.5"
            style={{ background:"rgba(255,255,255,0.03)", border:"1px solid rgba(255,255,255,0.07)" }}>
            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="rgba(255,255,255,0.30)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/>
            </svg>
            <span className="text-[10px] text-white/30 font-mono">{docCode}-{roomName.toLowerCase().replace(/[^a-z0-9]+/g,"-")}.txt</span>
          </div>

          <div className="flex flex-wrap gap-3">
            <button onClick={handleCopy}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-white/70 transition-all hover:text-white/90 hover:scale-105"
              style={{ background:"rgba(255,255,255,0.06)", border:"1px solid rgba(255,255,255,0.10)" }}>
              {copied
                ? <><CheckIco/> Copied!</>
                : <><CopyIco/> Copy to clipboard</>
              }
            </button>
            <button onClick={handleDownload}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-white transition-all hover:scale-105"
              style={{ background:"rgba(99,102,241,0.18)", border:"1px solid rgba(99,102,241,0.30)" }}>
              <DlIco/> Download .txt
            </button>
            <button onClick={fetchCalLinks}
              className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-semibold text-white/65 transition-all hover:text-white/85"
              style={{ background:"rgba(255,255,255,0.05)", border:"1px solid rgba(255,255,255,0.09)" }}>
              📅 Schedule next
            </button>
          </div>

          {/* Calendar links */}
          <AnimatePresence>
            {showCal && (
              <motion.div initial={{ opacity:0, height:0 }} animate={{ opacity:1, height:"auto" }} exit={{ opacity:0, height:0 }}
                className="overflow-hidden mt-4">
                <div className="flex flex-col gap-2 pt-1">
                  {calLinks ? (
                    <>
                      <a href={calLinks.google} target="_blank" rel="noreferrer"
                        className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold text-white hover:scale-[1.02] transition-transform"
                        style={{ background:"rgba(66,133,244,0.18)", border:"1px solid rgba(66,133,244,0.28)" }}>
                        📅 Add to Google Calendar
                      </a>
                      <a href={calLinks.outlook} target="_blank" rel="noreferrer"
                        className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold text-white hover:scale-[1.02] transition-transform"
                        style={{ background:"rgba(0,120,212,0.18)", border:"1px solid rgba(0,120,212,0.28)" }}>
                        📆 Add to Outlook
                      </a>
                    </>
                  ) : (
                    <div className="flex items-center gap-2 text-white/30 text-xs py-2">
                      <div className="w-4 h-4 rounded-full border border-indigo-500/40 border-t-indigo-500 animate-spin"/>
                      Generating calendar links…
                    </div>
                  )}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </motion.div>

        {/* ── Bottom actions ── */}
        <motion.div initial={{ opacity:0 }} animate={{ opacity:1 }} transition={{ delay:0.4 }}
          className="flex items-center justify-between">
          <button onClick={onHome}
            className="text-sm text-white/28 hover:text-white/58 transition-colors flex items-center gap-1.5">
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="15 18 9 12 15 6"/>
            </svg>
            Back to home
          </button>
          <button onClick={onNewMeeting}
            className="flex items-center gap-2 px-8 py-3 rounded-xl text-sm font-bold text-white transition-all hover:scale-105"
            style={{ background:"linear-gradient(135deg,#6366f1,#4f46e5)", boxShadow:"0 0 20px rgba(99,102,241,0.30)" }}>
            <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><polygon points="5 3 19 12 5 21 5 3"/></svg>
            New meeting
          </button>
        </motion.div>
      </div>
    </div>
  );
}

const SLabel = ({ icon, text }) => (
  <div className="flex items-center gap-2 text-[9px] font-black uppercase tracking-widest text-white/25">
    <span>{icon}</span>{text}
  </div>
);
const CopyIco  = () => <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>;
const DlIco    = () => <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>;
const CheckIco = () => <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>;
